### PR TITLE
ci: use the new flaky analyser

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Use the new flaky analyser approach:

- elastic/apm-pipeline-library#1038

## Why is it important?

Flaky analyser has been reimplemented, let's use the new implementation

### CODE REVIEW

**Review by mdelapenya — COMMENTED** [review]
LGTM, although there is an error in the unit test stage:

>java.util.regex.Matcher

👍  when this is fixed

**Comment by v1v** [comment]
> LGTM, although there is an error in the unit test stage:

I'm not sure why it happens, it seems unrelated to these changes. right?

**Review by mdelapenya — APPROVED** [review]

**Comment by adam-stokes** [comment]
> I'm not sure why it happens, it seems unrelated to these changes. right?

Those failures are related to a known issue where the agent's aren't going into a successful offline status #895

**Pull request merged**
