### PR TITLE
Temporary fix for revoke token tests

### PR DESCRIPTION
**Pull request by adam-stokes**
There seems to be a time gap between when an enrollment token is deleted and
when the stack actually knows it is deleted.

Ref: https://github.com/elastic/kibana/issues/105078

Signed-off-by: Adam Stokes <51892+adam-stokes@users.noreply.github.com>

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the Unit tests (`make unit-test`), and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by kuisathaverat — APPROVED** [review]

**Comment by cachedout** [comment]
I confess to being a bit confused by this.

This seems like you've [filed it as a legitimate bug](https://github.com/elastic/kibana/issues/105078). Shouldn't this test fail until the issue is resolved?

**Comment by mdelapenya** [comment]
Adding backport to 7.x too

**Comment by mdelapenya** [comment]
> I confess to being a bit confused by this.
> 
> This seems like you've [filed it as a legitimate bug](https://github.com/elastic/kibana/issues/105078). Shouldn't this test fail until the issue is resolved?

I agree with @cachedout, it shouldn't wait that long for a token to be invalidated. I've read their explanation in https://github.com/elastic/kibana/issues/105078#issuecomment-878407168, although I miss a reference on how to modify that default value to something shorter in tests.

**Comment by mdelapenya** [comment]
Opened an issue in the fleet-server repo asking for a configurable property: https://github.com/elastic/fleet-server/issues/568

**Pull request merged**
