### PR TITLE
fix: honor ELASTIC_AGENT_VERSION when downloading the agent (#480) backport for 7.10.x

### PR DESCRIPTION
**Pull request by mdelapenya**
Backports the following commits to 7.10.x:
 - fix: honor ELASTIC_AGENT_VERSION when downloading the agent (#480)

### CODE REVIEW

**Comment by mdelapenya** [comment]
I know why this is failing: because we are setting the ELASTIC_AGENT_VERSION to `7.10-SNAPSHOT` in the Jenkinsfile, it's directly used to get the variable, but it's indeed an alias, not a version.

I see two options here:

a. check if the version set in the environment is an alias (more code to maintain)
b. remove the default value in the Jenkinsfile, honouring the base version (simplify the Jenkinsfile, setting default values to empty, making version bumps easier: less locations for the version). My option is this one 🤚 

@elastic/observablt-robots thoughts?

**Review by kuisathaverat — APPROVED** [review]

**Review by cachedout — APPROVED** [review]

**Comment by mdelapenya** [comment]
As discussed offline, I'll set the Jenkinsfile parameters with empty values

**Comment by mdelapenya** [comment]
> As discussed offline, I'll set the Jenkinsfile parameters with empty values

Upsss... after setting that variable as empty in the pipeline, the job failed with:

>[2020-12-02T16:17:27.052Z] ERROR: groovy.lang.MissingPropertyException: No such property: METRICBEAT_VERSION for class: groovy.lang.Binding

**Comment by mdelapenya** [comment]
jenkins run the tests please

**Pull request closed without merging**
