### PR TITLE
chore: bump versions for 7.12.x

### LINKED ISSUE #802: Create 7.12.x branch
It must run the tests against Beats 7.12 branch

@EricDavisX @michalpristas should we deprecate 7.10.x after that?

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It bumps the versions for this project: Elastic stack, metricbeat and elastic-agent.

We are going to use the 7.12 alias (7.12-SNAPSHOT), as it will be internall resolved to the proper snapshot.

## Why is it important?
Support for the 7.12 release

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests for the CLI, and they are passing locally
- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ] @michalpristas Is the Stale agent version correct?

## Related issues

- Closes #802

### CODE REVIEW

**Comment by mdelapenya** [comment]
Failing all metricbeat tests because `docker.elastic.co/beats/metricbeat:7.12-SNAPSHOT` does not exist in the container library.

**Review by cachedout — APPROVED** [review]

**Comment by michalpristas** [comment]
looks ok

**Comment by mdelapenya** [comment]
jenkins run the tests please

**Comment by mdelapenya** [comment]
Merging, as the 7.12-SNAPSHOT images are now pushed and the CI passed

**Pull request merged**
