### PR TITLE
Update K8s and Kind version

### PR DESCRIPTION
**Pull request by constanca-m**
## What does this PR do?

Update K8s and Kind version being used in testing to support 1.27 K8s version.

Edit: Changing go to 1.20.5 instead of the being used 1.20.7, because it is causing errors on docker.

## Related issues

Relates to https://github.com/elastic/observability-dev/issues/2531.

### CODE REVIEW

**Review by MichaelKatsoulis — APPROVED** [review]

**Comment by gizas** [comment]
@elastic/ci-robots do you have any clue why this is failing? 
See e2e failures here: https://github.com/elastic/e2e-testing/actions/runs/5809087396/job/15747194121?pr=3612

**Pull request merged**
