### PR TITLE
chore: rename arm64 to aarch64 for tar.gz files

### LINKED ISSUE #1781: Rename arm64 suffix to aarch64 for tar.gz files
See Beats PR: https://github.com/elastic/beats/pull/28813 and Issue: https://github.com/elastic/beats/issues/28738

As @v1v points out, this only applies to `versions >= 8`

### PR DESCRIPTION
**Pull request by mdelapenya**
- chore: rename arm64*.tar.gz to aarch64*.tar.gz
- chore: handle aarch64 architecture in Go
- chore: handle aarch64 in Jenkins
- chore: rename gherkin tags

## What does this PR do?
It renames arm64 artifacts to aarch64

## Why is it important?
The Beats team wants to standardize the names of their build artifacts and we must be ready for that change

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the Unit tests (`make unit-test`), and they are passing locally
- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ] @adam-stokes, be aware of this PR for your VM implementation, as it touches how the archiitecture is read

## Related issues

- Closes #1781
- Relates elastic/beats#28813 and elastic/beats#28738

### CODE REVIEW

**Comment by adam-stokes** [comment]
This may need to hold off on merging until https://github.com/elastic/e2e-testing/pull/1740 is done

**Comment by v1v** [comment]
https://github.com/elastic/beats/pull/28813 has been now merged, so a new snapshot will be created in the near future

**Comment by v1v** [comment]
This won't be needed for the time being. https://github.com/elastic/beats/pull/30083 has been opened to discard the changes. We will revisit the renaming in the future

**Comment by mdelapenya** [comment]
Ok, let's close this one and revisit it if needed. Thanks for the ping!

**Pull request closed without merging**
