### PR TITLE
chore: remove slack notifications to infra-release-notify

### PR DESCRIPTION
**Pull request by jmlrt**
This commit is removing the Slack notifications to
`#infra-release-notify` channel.

Following elastic/observability-robots#1002,
the ownership of o11y Helm charts should move to o11y team.

cc @elastic/infra-release

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]

**Comment by jmlrt** [comment]
👋🏻 @mdelapenya, is there something to do to fix the 2 failing tests, or should we admin-merge? In addition, is there a need to backport to other branches?

**Comment by mdelapenya** [comment]
The errors are not related to this PR, and they are in upstream (we are on it).

About the backports, we do run the Helm charts tests for main (== 8.1.0-SNAPSHOT), main-1 (8.0.0-SNAPSHOT) and main-2 (7.17 and 7.16), so we still need this backported

**Comment by jmlrt** [comment]
Thanks 👍🏻 
I've added the backport labels and will let you merge when tests are fixed upstream then.

**Comment by mdelapenya** [comment]
> Thanks 👍🏻 I've added the backport labels and will let you merge when tests are fixed upstream then.

I think we are good to merge even though the upstream tests are broken, as we are in the middle of stabilising them.

Thanks for your help here

**Pull request merged**
