### PR TITLE
feat: support for RedHat Ubi 7

### LINKED ISSUE #239: Add test support in Ingest Manager suite for Red Hat UBI Agent Docker container
see comments here: https://github.com/elastic/integrations-dev/issues/188
 - we can likely copy + paste the current Agent stand-alone test and re-run it with this container instead in the config.

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It adds support for RedHat UBI, but to achieve it the developer (or the CI) has to login in RedHat registry, so docker pull works.

We simply added a new installer, reusing the Centos one, and added a new example in the scenario ooutlline for the restart agent.

## Why is it important?
It adds coverage in another platform.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests for the CLI, and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [x] Created personal account in RedHat Developers to gain access to the registry, checking that the image is pulled

## Related issues

- Closes #239

## Follow-ups
@elastic/observablt-robots we need to enable login access to the RedHat registry for the CI: 
```shell
docker login registry.redhat.io -u CI_USER
```

We could add a cache for the installers, as with this PR we are downloading RPM artifact twice.

We could also run all Fleet scenarios using Outline, so all of them are run in the different supported platforms

### CODE REVIEW

**Comment by mdelapenya** [comment]
The test will fail because there is no access to the registry yet

**Comment by mdelapenya** [comment]
Verified that, with the image already pulled, the agent service is not restarted after the container is restarted:

```
[root@e38feda9561e /]# systemctl status elastic-agent
● elastic-agent.service - Agent manages other beats based on configuration provided.
   Loaded: loaded (/usr/lib/systemd/system/elastic-agent.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://www.elastic.co/products/beats/elastic-agentv
```

**Review by cachedout — APPROVED** [review]

**Comment by mdelapenya** [comment]
Refactor this pull to use docker pull docker.elastic.co/beats/elastic-agent-ubi8:8.0.0-SNAPSHOT and docker pull docker.elastic.co/beats/elastic-agent-ubi8:7.10.0-SNAPSHOT

**Comment by mdelapenya** [comment]
@EricDavisX @jsoriano I guess that the new UBI images apply for the stand-alone mode, right?

**Comment by jsoriano** [comment]
> @EricDavisX @jsoriano I guess that the new UBI images apply for the stand-alone mode, right?

Not sure what is the scope of stand-alone mode in this context. But I think so, yes, the new images would apply on any scenario where we are using the releaseable docker images.

So, in principle any test suite where we are using `docker.elastic.co/beats/elastic-agent:VERSION`, should also pass with `docker.elastic.co/beats/elastic-agent-ubi8:VERSION`.

**Comment by EricDavisX** [comment]
@mdelapenya To your question, yes... I think this pr as it is, does not test the new Elastic created ubi image.  

But, it does however, test the Red Hat Docker image and uses the Fleet Mode (which has more test coverage in general than the stand-alone mode tests).  This PR is still very valuable, not just for the added test coverage, but as an excellent template we can follow to create any more OS / environment support tests as in:
https://github.com/elastic/e2e-testing/issues/252

Hence I'm tagging it and we can reference this when we get to it.  I think if tests are passing when we update the branch we should continue on with it and merge in

**Review by EricDavisX — APPROVED** [review]
lgtm

**Comment by EricDavisX** [comment]
we have the Ubi support implemented separately - we can close this. @mdelapenya will do so now.

**Comment by EricDavisX** [comment]
posting the ubi 7 pr just for completeness:  https://github.com/elastic/e2e-testing/pull/269

**Pull request closed without merging**
