### PR TITLE
Changing minimumHitsCount from 50 to 25

### LINKED ISSUE #1247: Reduce the number of documents that are verified in the stand-alone mode
cc/ @EricDavisX 

We are currently waiting for 50 docs in the index, and it takes +4 min to reach that number:

> [2021-06-09T13:00:15.261Z] time="2021-06-09T13:00:14Z" level=info msg="Hits number satisfied" currentHits=50 desiredHits=50 elapsedTime=4m34.393628738s retries=57

OTOH, it takes ~30secs to have 25 docs in the index:

> [2021-06-09T12:55:58.421Z] time="2021-06-09T12:55:58Z" level=warning msg="Waiting for more hits in the index" currentHits=0 desiredHits=50 elapsedTime=17.776235468s index=logs-elastic_agent-default retry=7

> [2021-06-09T12:56:01.635Z] time="2021-06-09T12:56:01Z" level=warning msg="Waiting for more hits in the index" currentHits=24 desiredHits=50 elapsedTime=21.333274089s index=logs-elastic_agent-default retry=8

> [2021-06-09T12:56:08.697Z] time="2021-06-09T12:56:08Z" level=warning msg="Waiting for more hits in the index" currentHits=25 desiredHits=50 elapsedTime=28.175342997s index=logs-elastic_agent-default retry=9

What do you think about reducing that amount of docs? We will be cutting down almost 3 mins to the stand-alone parallel branch in the build.

## Screenshots
This is a capture of the APM traces for the span representing the step `there is new data in the index from agent`:
Screenshot 2021-06-10 at 10 25 58

### PR DESCRIPTION
**Pull request by IgorGuz2000**
## What does this PR do?
Changing minimumHitsCount from 50 to 25

## Why is it important?
This PR will reduce running time of selected tests from 10 to 3 min

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests (`make unit-test`), and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ]

## How to test this PR locally
Run stand-alone test with @deploy-stand-alone tag

### CODE REVIEW

**Review by EricDavisX — APPROVED** [review]
looks good to me.

**Comment by adam-stokes** [comment]
This looks good to me, I'm investigating the test failures as there seems to be something else going on not related to this PR

**Comment by IgorGuz2000** [comment]
Yes Looks like the errors are not related to this PR

**Review by mdelapenya — APPROVED** [review]

**Comment by mdelapenya** [comment]
> This looks good to me, I'm investigating the test failures as there seems to be something else going on not related to this PR

I opened an investigation in #1274

**Comment by mdelapenya** [comment]
@IgorGuz2000 thanks for this contribution! It will make an impact in the build time :)

**Pull request merged**
