### PR TITLE
fix: use proper format for kibana's server host

### LINKED ISSUE #1194: [7.x] Kibana is not able to start
See https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/job/7.x/537/artifact/docker_logs_fleet_agent_endpoint_integration%20&&%20~@nightly.log

>[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z] 
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]  FATAL  Error: Invalid server options  {
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]   "port": 5601,
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]   "routes": {
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]     "cache": {
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]       "privacy": "private",
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]       "otherwise": "private, no-cache, no-store, must-revalidate"
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]     },
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]     "cors": false,
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]     "payload": {
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]       "maxBytes": 1048576
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]     },
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]     "validate": {
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]       "failAction": function defaultValidationErrorHandler(request, h, err) {\n    // Newer versions of Joi don't format the key for missing params the same way. This shim\n    // provides backwards compatibility. Unfortunately, Joi doesn't export it's own Error class\n    // in JS so we have to rely on the `name` key before we can cast it.\n    //\n    // The Hapi code we're 'overwriting' can be found here:\n    //     https://github.com/hapijs/hapi/blob/master/lib/validation.js#L102\n    if (err && err.name === 'ValidationError' && err.hasOwnProperty('output')) {\n        const validationError = err;\n        const validationKeys = [];\n        validationError.details.forEach((detail) => {\n            if (detail.path.length > 0) {\n                validationKeys.push(hoek_1.default.escapeHtml(detail.path.join('.')));\n            }\n            else {\n                // If no path, use the value sigil to signal the entire value had an issue.\n                validationKeys.push('value');\n            }\n        });\n        validationError.output.payload.validation.keys = validationKeys;\n    }\n    throw err;\n},
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]       "options": {
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]         "abortEarly": false
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]       }
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]     }
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]   },
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]   "state": {
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]     "strictHeader": false,
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]     "isHttpOnly": true,
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]     "isSameSite": false
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]   },
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z]   "host" [31m[1][0m: "0"
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z] }
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z] [31m
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z] [1] "host" must be a valid hostname[0m
[fleet_kibana_1][docker.elastic.co/kibana/kibana:7.14.0-SNAPSHOT][86d0036c937872ec03c29dbd5ac28d347a691b005fbd39b69b5958cc8605fa3d][2021-05-24T09:01:39.011Z] 
[frosty_jackson][docker.elastic.co/beats/filebeat:7.11.2][50cbe970db03785389751f3210575d23d988c79cb293ce375bef8f355d38a85b][2021-05-24T09:01:39.680Z] 2021-05-24T09:01:39.680Z	INFO	[monitoring]	log/log.go:144	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cgroup":{"cpuacct":{"total":{"ns":267814506}},"memory":{"mem":{"usage":{"bytes":589824}}}},"cpu":{"system":{"ticks":150,"time":{"ms":95}},"total":{"ticks":550,"time":{"ms":270},"value":550},"user":{"ticks":400,"time":{"ms":175}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":19},"info":{"ephemeral_id":"4a8b3ca9-9dc4-4d90-ac7a-77dd00534558","uptime":{"ms":90084}},"memstats":{"gc_next":20368160,"memory_alloc":11727832,"memory_total":73278072,"rss":76066816},"runtime":{"goroutines":75}},"filebeat":{"events":{"active":41,"added":208,"done":167},"harvester":{"open_files":4,"running":4,"started":1}},"libbeat":{"config":{"module":{"running":4,"starts":1}},"output":{"events":{"acked":166,"active":0,"batches":24,"total":166},"write":{"bytes":71521}},"pipeline":{"clients":4,"events":{"active":42,"filtered":1,"published":207,"total":208},"queue":{"acked":166}}},"registrar":{"states":{"current":4,"update":167},"writes":{"success":32,"total":32}},"system":{"load":{"1":3.53,"15":0.64,"5":1.65,"norm":{"1":0.4413,"15":0.08,"5":0.2063}}}}}}

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It uses a proper format for the value of kibana's server host, matching that value with other maintenance branches (master, 7.13, 7.12, 7.11)

## Why is it important?
Kibana cannot start, therefore the runtime dependencies for the tests are not satisfied, causing the entire test suite to fail.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the Unit tests for the CLI, and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ] Kibana seems to prevent the '0' value, although I checked its docs and it's not updated: https://github.com/elastic/kibana/blame/7.x/docs/setup/docker.asciidoc#L146. Will check Kibana's git history for 7.x to bisect when/where that change was introduced and to update the docs.

## Related issues

- Fixes #1194

### CODE REVIEW

**Review by v1v — APPROVED** [review]

**Comment by mdelapenya** [comment]
@watson are you aware of a change in 7.x about this issue? I remember a warning was added in https://github.com/elastic/kibana/pull/87471, but since friday, the 7.x kibana build is not able to start because of the server host issue. Please see log error in #1194. I'd appreciate if you are able to point me to the possible change, as I haven't been able to find it yet.

**Comment by watson** [comment]
Hmm `7.x` should still support using `0` as the `server.host`, just outputting a deprecation warning. Support for using just `0` seems to have been removed in #100378. Last time this was discussed this was considered a breaking change, so I assume it's accidental. ping @elastic/kibana-core

**Comment by mdelapenya** [comment]
Thanks! We will revert this commit to represent the current state of 7.x in Kibana.

**Comment by pgayvallet** [comment]
> Support for using just 0 seems to have been removed in elastic/kibana#100378.

Not sure how I did mess up that backport, but that was a mistake, yes. `0` should still be supported on `7.x`. Thanks for https://github.com/elastic/kibana/pull/100551.

**Comment by watson** [comment]
@pgayvallet I've merged the fix into `7.x` now. Thanks for spotting this 👍

**Pull request merged**
