### PR TITLE
fix: run linux integration on CI

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It includes the linux integration scenarios in the CI job, as a new parallel branch

## Why is it important?
This suite was missing from CI execution

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests for the CLI, and they are passing locally
- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

### CODE REVIEW

**Comment by jalvz** [comment]
Shouldn't we do something so that every new scenario added is executed on CI without more ceremony? ie, have the option maybe to opt out in case it is useful, instead of having to opt in.

**Review by kuisathaverat — APPROVED** [review]

**Comment by mdelapenya** [comment]
> Shouldn't we do something so that every new scenario added is executed on CI without more ceremony? ie, have the option maybe to opt out in case it is useful, instead of having to opt in.

Agree There is an open issue to standardise the tags used in feature files, which could simplify how they are spread across the different parallel executions. I can picture this:

1. list all feature files
2. change how the Make goals run the tests: instead of the tags use the file (`-f $THE_FEATURE_FILE`)
3. generate the descriptor file on the fly based on a template, using one feature file per parallel branch
4. update calls to make goals to not pass tags

If this makes sense to you, we can convert this comment into a new issue to start working on it, as I totally agree with you about the ceremonies :)

**Comment by mdelapenya** [comment]
Another idea, related to the used tags, could be to group all integrations under the `@integration` tag, and run them all together: we'd have endpoint and linux integration under the same parallel execution on CI

**Comment by jalvz** [comment]
> change how the Make goals run the tests: instead of the tags use the file (-f $THE_FEATURE_FILE)

could we be even a folder?

**Comment by mdelapenya** [comment]
> > change how the Make goals run the tests: instead of the tags use the file (-f $THE_FEATURE_FILE)
> 
> could we be even a folder?

Yes, or a glob expression: *.feature. but on CI we want to create a separation of concerns power feature, to speed up the build

**Pull request merged**
