### PR TITLE
chore: bump helm-charts + helm version

### PR DESCRIPTION
**Pull request by jmlrt**
- bump helm-charts to 7.10.0 which is fully compatible with Helm 3
- update tests for metricbeat 7.10.0
- bump Helm version to 3.4.1 which is used in helm-charts repo

### CODE REVIEW

**Comment by mdelapenya** [comment]
LGTM 👍  Let's see the CI green to merge, thank you!!!

image

**Comment by mdelapenya** [comment]
@jmlrt there is a failure in the metricbeat scenario, more specifically in this step: https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/helm/features/metricbeat.feature#L11

>[2020-11-24T12:14:13.346Z] time="2020-11-24T12:14:06Z" level=error msg="Error executing command" args="[get configmap metricbeat-metricbeat-config -o jsonpath=\"{.data['metricbeat\\.yml']}\"]" baseDir=. command=kubectl error="exit status 1" stderr="Error from server (NotFound): configmaps \"metricbeat-metricbeat-config\" not found\n"

**Review by cachedout — APPROVED** [review]

**Review by kuisathaverat — APPROVED** [review]

**Comment by jmlrt** [comment]
I updated Metricbeat test to make it pass 🤞  but that could be improved to check every resources of the charts.

For example Metricbeat charts deploy 2 config-maps now: `metricbeat-metricbeat-deployment-config` and `metricbeat-metricbeat-daemonset-config` but [`getResourceName`](https://github.com/jmlrt/e2e-testing/blob/3c485b43dee6098f20cd197151c0e53626b9fa4d/e2e/_suites/helm/helm_charts_test.go#L307-L326), only allows to check one config map for each chart.

I'll try to rework it later.

**Comment by mdelapenya** [comment]
@jmlrt this looks good to me! The tests are passing and the only failed test is about Go format that is not added by your code. I'd merge as is if you think it's finished

**Comment by jmlrt** [comment]
OK let's merge it and I'll try to submit another PR later :)

**Pull request merged**
