### PR TITLE
fix: use "0.0.0.0" string instead of null for ES' network.host

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It uses an empty string (`"0.0.0.0"`) instead of the null value for `network.host` in the elasticsearch confioguration.

## Why is it important?
We detected that 8.3-SNAPSHOT is not able to start because of that:

```java
Exception in thread "main" org.elasticsearch.ElasticsearchParseException: null-valued setting found for key [network.host] found at line number [5], column number [14]
	at org.elasticsearch.common.settings.Settings.validateValue(Settings.java:767)
	at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:743)
	at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:687)
	at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1189)
	at org.elasticsearch.node.InternalSettingsPreparer.loadOverrides(InternalSettingsPreparer.java:143)
	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:53)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:109)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:53)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:94)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:87)
	at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:57)
```

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests (`make unit-test`), and they are passing locally
- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ]

## How to test this PR locally
From the main branch, run this command to start the stack:

```shell
TAGS="badabumnightly" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true ELASTIC_APM_ACTIVE=false  make -C e2e/_suites/fleet functional-test
```

## Related issues

- Could be related to https://github.com/elastic/elasticsearch/pull/80042 or https://github.com/elastic/elasticsearch/pull/83145

### CODE REVIEW

**Review by v1v — APPROVED** [review]

**Review by v1v — CHANGES_REQUESTED** [review]
The description/title does not match with the implementation, changes are about `0.0.0.0` instead `""`

**Comment by mdelapenya** [comment]
> The description/title does not match with the implementation, changes are about `0.0.0.0` instead `""`
> 
> In case, it will add a regression

Ah yes, sorry, I did a rebase interactive while sending the PR 🤦  I first used the elastic-agent folks' implementation after searching for the elasticsearch issues

**Comment by mdelapenya** [comment]
I verified that the docker container for ES is starting:
- SSH into the machine
- login as root
- docker ps && docker logs

**Review by kuisathaverat — APPROVED** [review]

**Review by v1v — APPROVED** [review]
Do you think this particular change should be backported only in >=8.2 ?

**Comment by mdelapenya** [comment]
> Do you think this particular change should be backported only in >=8.2 ?

Indeed. Because the container is able to start in 8.1, 8.2 and 7.17. We may keep it in main branch.

I took a look at the elastic-package code and checked they use the same for 8_x than for main: https://github.com/elastic/elastic-package/tree/main/internal/profile/_static, that's why I added the other backport labels.

I'm going to remove them all, so that no backport is need. Thanks for the suggestion!

**Review by amannocci — APPROVED** [review]

**Pull request merged**
