### PR TITLE
Update .e2e-tests.yaml to add windows srv 2022

### PR DESCRIPTION
**Pull request by jlind23**
Add Windows server 2022 as an operating system on which fleet server and elastic agent tests will be deployed.

### CODE REVIEW

**Comment by jlind23** [comment]
@mdelapenya it seems to be the same test failing on each PR. Can we fix it?

**Comment by mdelapenya** [comment]
> @mdelapenya it seems to be the same test failing on each PR. Can we fix it?

The windows stage did fail: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/PR-2023/1/pipeline, @adam-stokes is looking into it.

And for the existing failure, there is an open issue, but I think it's not related to the tests but to the elastic-agent container. Please more details here: #1992, which links to https://github.com/elastic/beats/issues/29811 as root cause

**Comment by jlind23** [comment]
@adam-stokes @mdelapenya anything I can do here on my end?

**Comment by adam-stokes** [comment]
This requires a bit more work to support it in ansible, I'll need to get some additional tasks written to support winrm etc

**Comment by jlind23** [comment]
@adam-stokes Should I close it for now? I also wanted to add Windows 11 but i'm quite sure I am going to face the same issue right?

**Comment by adam-stokes** [comment]
@jlind23 I'd leave it open, I'll reference it when I can complete the work

**Comment by jlind23** [comment]
@adam-stokes any update there?

**Comment by cachedout** [comment]
@adam-stokes Could you please update this issue with the latest status? Please let me know if we need to reflect the work that needs to be done here in our sprint planning if it isn't already. Let's try to get @jlind23 unblocked if we can. :)

**Comment by jlind23** [comment]
@cachedout is there any progress that can be shared here?

**Comment by cachedout** [comment]
@jlind23 We had to move @adam-stokes over to a more urgent project temporarily. I don't think there's any news to share on this at the moment, unfortunately.

**Comment by mdelapenya** [comment]
I'm going to close this one in favour of #2338, which I've started a local branch for it

Please reopen if you have any consideration about it

**Pull request closed without merging**
