### PR TITLE
chore: double Helm max timeout

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It adds a global variable setting the max timeout factor to 2. This variable could be modified by an environment variable, set on CI to 3.

## Why is it important?
It will make the backoff strategies configurable on test time, because it's now fixed to 1 minute.

After a few builds with the new Helm 3 code, it seems to randomly fail for metricbeat, that's why we are allowing this configuration.

Besides that, we noticed that installing the Elasticsearch helm chart took a lot. We found that there was a hardcoded value for the timeout, so we are reusing the new variable here to build the max timeout, also reducing the value from 900s to 200s by default (300 on CI).

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests for the CLI, and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## How to test this PR locally
```shell
SUITE="helm" TAGS="metricbeat" DEVELOPER_MODE=true TIMEOUT_FACTOR=1 LOG_LEVEL=TRACE make -C e2e functional-test
```

If using TIMEOUT_FACTOR=1, then you'll see this log in the output console (pay attention to the `--timeout=100s`):
>ERRO[2020-11-25T19:12:29+01:00] Error executing command                       args="[install elasticsearch elastic/elasticsearch --version 7.10.0 --wait --timeout=100s --values https://raw.githubusercontent.com/elastic/helm-charts/master/elasticsearch/examples/kubernetes-kind/values.yaml]" baseDir=. command=helm error="exit status 1" stderr="Error: timed out waiting for the condition\n"

## Related issues

- Relates #447

## Follow-ups
Backports to 7.x, 7.9.x and 7.10.x are required

### CODE REVIEW

**Review by kuisathaverat — APPROVED** [review]

**Comment by mdelapenya** [comment]
@jmlrt I sent this PR after finding this error when installing the Elasticsearch helm chart:

>TRAC[2020-11-25T18:39:08+01:00] Executing command                             args="[install elasticsearch elastic/elasticsearch --version 7.10.0 --wait --timeout=900s --values https://raw.githubusercontent.com/elastic/helm-charts/master/elasticsearch/examples/kubernetes-kind/values.yaml]" command=helm
>ERRO[2020-11-25T18:54:13+01:00] Error executing command                       args="[install elasticsearch elastic/elasticsearch --version 7.10.0 --wait --timeout=900s --values https://raw.githubusercontent.com/elastic/helm-charts/master/elasticsearch/examples/kubernetes-kind/values.yaml]" baseDir=. command=helm error="exit status 1" stderr="Error: timed out waiting for the condition\n"
ERRO[2020-11-25T18:54:13+01:00] Could not install runtime dependency          dependency=elasticsearch error="exit status 1"

which is thrown when applying a workaround to use Rancher's local-path storage class for Elasticsearch volumes.

Do you think we can remove/update it?

**Comment by mdelapenya** [comment]
I did not mention it, but the tests continue after the 900 seconds timeout wait, which makes me think we do not need it

**Review by v1v — APPROVED** [review]

**Comment by jmlrt** [comment]
We also saw a lot of errors related to timeouts in our CI tests recently.

I just updated the timeout from 900s to 1200s

https://github.com/elastic/helm-charts/blob/87be9d6a19787a1990d43d40bb326482eb049879/elasticsearch/examples/kubernetes-kind/Makefile#L4

>I did not mention it, but the tests continue after the 900 seconds timeout wait, which makes me think we do not need it

AFAIK, `--timeout` should fail the `helm install` command after the specified duration if pods aren't yet in ready state, does `kubectl.Run` fail the program if the command fail?

Not that if the pods aren't ready yet, the command fail, but the deployed resources aren't cleaned so pods may eventually become ready after the timeout.

**Comment by mdelapenya** [comment]
> AFAIK, `--timeout` should fail the `helm install` command after the specified duration if pods aren't yet in ready state, does `kubectl.Run` fail the program if the command fail?

It does, but for runtime dependencies of the charts (only elasticsearch at the moment) it does not.

**Pull request merged**
