### PR TITLE
Igor Agent upgrade test fix

### PR DESCRIPTION
**Pull request by IgorGuz2000**
## What does this PR do?
This scenario Need to be fixed it never installed stale agent version. If you use 7.16 branch it will install 7.16 agent and upgrade to 7.16 agent. I will open the Ticket to fix this

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests (`make unit-test`), and they are passing locally
- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by mdelapenya** [comment]
@michalpristas could you take a look? It seems @IgorGuz2000 found a real bug here, thanks!

**Comment by mdelapenya** [comment]
@michalpristas, as author of that test scenario, we'd need your help with this 🙏

**Comment by jlind23** [comment]
@adam-stokes @mdelapenya can we move it back to life?
How can we help there?
cc @ph

**Comment by mdelapenya** [comment]
After #2354 I think this can be closed

**Pull request closed without merging**
