### PR TITLE
fix: use file realm for security users

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
This PR adds an ES setting to use the file realm for security users:

```
xpack.security.authc.realms.file.file1.order=0
```

## Why is it important?
The ES team recommended to use the file realm instead for integration testing

With this change we expect to reduce flakiness in certain tests

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests for the CLI, and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

### CODE REVIEW

**Comment by mdelapenya** [comment]
It's weird: now it's not possible to set up Fleet

>[2020-08-19T06:20:44.318Z] time="2020-08-19T06:20:42Z" level=error msg="Could not initialise Fleet setup" body="{\"statusCode\":500,\"error\":\"Internal Server Error\",\"message\":\"[security_exception] unable to authenticate user [fleet_enroll] for REST request [/_security/api_key], with { header={ WWW-Authenticate={ 0=\\\"ApiKey\\\" & 1=\\\"Basic realm=\\\\\\\"security\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\" } } }\"}" error="POST request failed with 500" url="http://localhost:5601/api/ingest_manager/fleet/setup"

That's why all fleet tests failed

@ph @EricDavisX any guess?

**Review by v1v — APPROVED** [review]

**Review by cachedout — APPROVED** [review]

**Comment by ph** [comment]
Thats seems a bug, File realm shouldn't affect that.

Is there something on the Kibana log?

@nchaulet Anything we could do to get more information.

**Comment by nchaulet** [comment]
The calls we do as the fleet user to create API key use basic auth, this means the `native` realm need to be enabled for Fleet to work.

This could be fixed if we were able to create API key from API key

**Comment by mdelapenya** [comment]
> ... this means the `native` realm need to be enabled for Fleet to work.

Is this documented anywhere? Does it mean that we can close this PR?

**Comment by ph** [comment]
@nchaulet @mdelapenya oh my I didn't know about that requirement on the native realm, that, I am sorry for that.

**Comment by mdelapenya** [comment]
> @nchaulet @mdelapenya oh my I didn't know about that requirement on the native realm, that, I am sorry for that.

No worries :) I'm closing this issue because @nchaulet's previous comment. Thanks!

**Pull request closed without merging**
