### PR TITLE
chore: stringify http responses

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It uses the string representation of the array of bytes that are responded by HTTP servers (particularly Kibana APIs).

## Why is it important?
When used in logs, it prints out the array of bytes instead of the String representation, making it useless to troubleshoot any log error

Instead of:
> time="2022-07-07T08:46:42Z" level=error msg="Could not get Fleet data streams api" body="[123 34 115 116 97 116 117 115 67 111 100 101 34 58 53 48 48 44 34 101 114 114 111 114 34 58 34 73 110 116 101 114 110 97 108 32 83 101 114 118 101 114 32 69 114 114 111 114 34 44 34 109 101 115 115 97 103 101 34 58 34 115 101 97 114 99 104 95 112 104 97 115 101 95 101 120 101 99 117 116 105 111 110 95 101 120 99 101 112 116 105 111 110 58 32 91 100 97 116 101 95 116 105 109 101 95 101 120 99 101 112 116 105 111 110 93 32 82 101 97 115 111 110 58 32 70 105 101 108 100 32 89 101 97 114 32 99 97 110 110 111 116 32 98 101 32 112 114 105 110 116 101 100 32 97 115 32 116 104 101 32 118 97 108 117 101 32 45 50 57 50 50 55 53 48 53 53 32 101 120 99 101 101 100 115 32 116 104 101 32 109 97 120 105 109 117 109 32 112 114 105 110 116 32 119 105 100 116 104 32 111 102 32 52 34 125]" error="<nil>" statusCode=500

we would have:
>time="2022-07-07T08:22:19Z" level=error msg="Could not get Fleet data streams api" body="{\"statusCode\":500,\"error\":\"Internal Server Error\",\"message\":\"search_phase_execution_exception: [date_time_exception] Reason: Field Year cannot be printed as the value -292275055 exceeds the maximum print width of 4\"}" error="<nil>" statusCode=500

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests (`make unit-test`), and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Related issues

- Relates to any automated bump in 8.4, which is froxen since June 6th
- Discovered while testing https://github.com/elastic/kibana/pull/135817

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
Are we certain that these responses will never contain sensitive information?

**Comment by mdelapenya** [comment]
> Are we certain that these responses will never contain sensitive information?

Aha, that's a good point. And TBH, this question should be answered by the Fleet team, which I expect them to consider those concerns.

As a consumer, the test execution should know what is the error kibana is throwing alongside a 500 HTTP code.

**Comment by cachedout** [comment]
@mdelapenya Thanks. Maybe we can get some insight from @joshdover here. Is there any reason to believe that just printing HTTP from Fleet Server to a log which is available to the public will ever result in the disclosure of sensitive information? I would assume not, but it never hurts to ask. :)

**Review by kuisathaverat — APPROVED** [review]

**Pull request merged**
