### PR TITLE
fix: bump stale agent to 7.17.2

### LINKED ISSUE #2326: Flaky Test [Initializing / End-To-End Tests / fleet_centos8_arm64_fleet_mode_agent / Upgrading the installed agent – Fleet Mode Agent]
## Flaky Test

* **Test Name:** `Initializing / End-To-End Tests / fleet_centos8_arm64_fleet_mode_agent / Upgrading the installed agent – Fleet Mode Agent`
* **Artifact Link:** https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2F7.17/detail/7.17/464/
* **PR:** None
* **Commit:** 6534fb8609444934bb9799c0dd4039e59ac1aa21

### Error details
```
Step certs are installed
```

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It bumps the stale agent version from 7.17.1 to 7.17.2

## Why is it important?
The 7.17.1 version disappeared from artifacts-api

I believe this upgrade agent scenario should be rewritten in a way that is not that sensible to the snapshot version, and instead uses a release version. For 7.17, it currently uses the branch's version minus 1 patch as a snapshot (see current changes), but this moving target is retired from the artifacts-api with certain frequency.

@v1v and I have mentioned a few times to detect the move and bump the stale agent version in an automated way, but I think it would be hiding the real problem of the sensitivity of this scenario.

@jlind23 @ph wdyt?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests (`make unit-test`), and they are passing locally
- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Related issues

- Closes #2326 #2325 #2324 
- Relates https://github.com/elastic/e2e-testing/issues/1643

### CODE REVIEW

**Comment by jlind23** [comment]
@mdelapenya my question is, shouldn't we update those tests at the same time as the 7.17.2 is created? If we go too slow then artifacts will be deleted. Bumping the version in an automated way as we do for other repositories should fix this particular behaviour.

**Comment by cachedout** [comment]
I don't understand why this is statically defined to begin with. Couldn't you just find the latest 7.x by querying [this API endpoint](https://artifacts-api.elastic.co/v1/versions/)?

**Comment by mdelapenya** [comment]
> @mdelapenya I don't understand why this is statically defined to begin with. Couldn't you just find the latest 7.x by querying [this API endpoint](https://artifacts-api.elastic.co/v1/versions/)?

Me neither. This test was designed by @michalpristas before he left, and we do maintain. As explained in the issue:

>I believe this upgrade agent scenario should be rewritten in a way that is not that sensible to the snapshot version, and instead uses a release version. For 7.17, it currently uses the branch's version minus 1 patch as a snapshot (see current changes), but this moving target is retired from the artifacts-api with certain frequency.

A refactor of the scenario, having the team directions should be needed

**Comment by michalpristas** [comment]
if i remember correctly there was something in framework which prevented me to go with dynamic versions.
if this is no longer the case refactor should take place rather than bumping up versions for sure

**Review by kuisathaverat — APPROVED** [review]

**Comment by mdelapenya** [comment]
@cachedout as described in https://github.com/elastic/e2e-testing/issues/1643#issuecomment-1091549380, the idea is to refactor the steps according to that upgrade matrix using releases. Therefore, we would have to maintain the upgradeable versions for each branch.

**Pull request merged**
