### PR TITLE
chore: run k8s and helm test suites on ARM

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It bumps the k8s and Kind versions to a version that supports ARM. For kind, it appeared in v0.11.0, which according to its changelog requires a 1.21.1 version of k8s.

## Why is it important?
We want to verify those test suites on ARM

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests (`make unit-test`), and they are passing locally
- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ]

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Review by jsoriano — APPROVED** [review]
LGTM if it looks good to jenkins :+1:

**Comment by mdelapenya** [comment]
@jmlrt we are bumping kind and k8s versions in this PR, and we see that APM Server helm chart fails consistently: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/PR-1471/6/tests

>Step a "Service" will expose the pods as network services internal to the k8s cluster

Are helm charts supporting k8s 1.21.1?

**Comment by jmlrt** [comment]
> @jmlrt we are bumping kind and k8s versions in this PR, and we see that APM Server helm chart fails consistently: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/PR-1471/6/tests
> 
> > Step a "Service" will expose the pods as network services internal to the k8s cluster
> 
> Are helm charts supporting k8s 1.21.1?

Not sure, I didn't tested them yet with 1.21. Is it also failing for filebeat and metricbeat charts or only apm-server?

**Comment by mdelapenya** [comment]
Only for APM Server, the other two pass as expected

**Comment by jmlrt** [comment]
@mdelapenya, I did some tests with apm-server 7.14.0 on GKE v1.21.3-gke.1100 which were successful.

However, I never tested these charts with ARM64 so I don't know if they are compatible.

Do you have a bit more details about what is failing?

**Comment by adam-stokes** [comment]
With the merging of #1740 I did attempt to get docker daemon running inside the arm VM's. Apparently, it is not as straightforward as amd64, but if we could get that working we can quickly expand our test matrix to include support for these suites on arm almost instantly.  This is all assuming that docker images, kind, k8s all play nicely together in a pure ARM environment.

**Comment by mdelapenya** [comment]
Closing as outdated

**Pull request closed without merging**
