### PR TITLE
chore(ci): be more specific about the underlying ARM OS

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It forces `centos-8-arm` as the label used by Jenkins to grab the CI workers when the tests need to be run on ARM.

## Why is it important?
We are seeing certain flakiness in one single scenario for Debian (See https://github.com/elastic/e2e-testing/issues/1271) and we'd like to narrow down the issue: because we have multiple ARM CI workers under the `arm` label, we want to always use the same.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests (`make unit-test`), and they are passing locally
- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ] The label does exist on Infra's catalog

## Related issues

- Relates https://github.com/elastic/e2e-testing/issues/1271
- Relates https://github.com/elastic/e2e-testing/issues/1340

### CODE REVIEW

**Review by v1v — APPROVED** [review]
Do you want to run this a few times a day? In case you'd like to add the cron option in the toplevel options section

**Review by cachedout — APPROVED** [review]

**Comment by mdelapenya** [comment]
> Do you want to run this a few times a day? In case you'd like to add the cron option in the toplevel options section

I'd say that with the current frequency it's enough, but I see your point: we could maybe keep a PR open simply running the offending test suite. 🤔 Does it make sense, right?

**Comment by v1v** [comment]
I thought this PR will remain open, that was the reason for my question, since it's merged then it was not valid :)

**Comment by mdelapenya** [comment]
We can send a new one simplifying the test layout, including the proposed cron

**Pull request merged**
